name: self_host
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.14.1
  encrypt: ^5.0.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^2.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
