# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Compile
        run: |
          mkdir dist
          cd self_host
          dart pub get
          dart compile exe bin/self_host.dart -o ../dist/dashboard-windows.exe
          cd ..

      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-windows
          path: dist/dashboard-windows.exe

  linux:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: true
        - name: Setup Dart
          uses: dart-lang/setup-dart@v1
  
        - name: Compile
          run: |
            mkdir dist
            cd self_host
            dart pub get
            dart compile exe bin/self_host.dart -o ../dist/dashboard-linux
            cd ..
  
        - name: Upload Dist Artifact
          uses: actions/upload-artifact@v4
          with:
            name: dashboard-linux
            path: dist/dashboard-linux

  macos:
    runs-on: macos-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: true
        - name: Setup Dart
          uses: dart-lang/setup-dart@v1
  
        - name: Compile
          run: |
            mkdir dist
            cd self_host
            dart pub get
            dart compile exe bin/self_host.dart -o ../dist/dashboard-macos
            cd ..
  
        - name: Upload Dist Artifact
          uses: actions/upload-artifact@v4
          with:
            name: dashboard-macos
            path: dist/dashboard-macos



  build_dashboard_index:
      name: Build Dashboard
      runs-on: ubuntu-latest
      needs:
        - linux
        - macos
        - windows

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: Install Dependencies
          run: |
            mkdir dist
            sudo apt-get update -y && sudo apt-get upgrade -y;
            sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa


        - name: Fetch Chrome
          uses: browser-actions/setup-chrome@v1
          id: setup-chrome
        - run: export CHROME_EXECUTABLE=${{ steps.setup-chrome.outputs.chrome-path }}

        - name: Setup Flutter SDK
          uses: flutter-actions/setup-flutter@v4
          with:
            channel: stable
            version: 3.22.1

        - name: Install dependencies
          run: flutter pub get

        - name: Build Dashboard
          run: flutter build web  --pwa-strategy none --web-renderer html

        - name: Zip
          run: |
            cd build/
            zip -r dashboard-index.zip web/
            mv dashboard-index.zip ../dist/
            cd ..

        - name: Upload Dashboard
          uses: actions/upload-artifact@v4
          with:
            name: dashboard-index
            path: dist/dashboard-index.zip


  publish_releases:
    name: publish
    runs-on: ubuntu-latest
    needs:
      - build_dashboard_index

    strategy:
      matrix:
        os: [windows, linux, macos]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Fetch Version
        run: |
          sudo snap install yq
          nbgui_version=$(yq eval '.version' pubspec.yaml)
          echo "NBGUI_VERSION=$nbgui_version" >> $GITHUB_ENV

      - name: Download Self-host Artifact
        uses: actions/download-artifact@v4
        with:
          name: "dashboard-${{ matrix.os }}"
          path: dist/

      - name: Download Dashboard Artifact
        uses: actions/download-artifact@v4
        with:
          name: "dashboard-index"
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NBGUI_VERSION }}
          body_path: RELEASE_CHANGELOG.md
          prerelease: false
          draft: false
          generate_release_notes: true
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          files: |
            dist/dashboard-windows.exe
            dist/dashboard-linux
            dist/dashboard-macos
            dist/dashboard-index.zip




