# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Compile
        run: |
          mkdir dist
          cd self_host
          dart pub get
          dart compile exe bin/self_host.dart -o ../dist/dashboard-windows.exe
          cd ..

      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-windows
          path: dist/dashboard-windows.exe

  linux_amd64:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: true
        - name: Setup Dart
          uses: dart-lang/setup-dart@v1
  
        - name: Compile
          run: |
            mkdir dist
            dart pub get
            dart compile exe bin/nonebot_flutter_webui_agent.dart -o dist/dashboard-linux-amd64
  
        - name: Upload Dist Artifact
          uses: actions/upload-artifact@v4
          with:
            name: dashboard-linux-amd64
            path: dist/dashboard-linux-amd64


  linux_arm64:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout
          uses: actions/checkout@v4


        - name: Install Dependencies
          run: |
            sudo apt update
            sudo apt install aria2 unzip -y
            aria2c https://storage.googleapis.com/dart-archive/channels/beta/release/3.7.0-209.1.beta/sdk/dartsdk-linux-arm64-release.zip
            unzip dartsdk-linux-arm64-release.zip
            rm dartsdk-linux-arm64-release.zip


        - name: Use ARM64 Environment to Compile
          uses: uraimo/run-on-arch-action@v2
          with:
            arch: aarch64
            distro: ubuntu20.04
            run: |
              export PATH=$PATH:$GITHUB_WORKSPACE/dart-sdk/bin
              mkdir dist
              dart pub get
              dart compile exe bin/nonebot_flutter_webui_agent.dart -o dist/dashboard-linux-arm64



        - name: Upload Dist Artifact
          uses: actions/upload-artifact@v4
          with:
            name: dashboard-linux-arm64
            path: dist/dashboard-linux-arm64


  linux_arm:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout
          uses: actions/checkout@v4


        - name: Install Dependencies
          run: |
            sudo apt update
            sudo apt install aria2 unzip -y
            aria2c https://storage.flutter-io.cn/dart-archive/channels/beta/release/3.7.0-209.1.beta/sdk/dartsdk-linux-arm-release.zip
            unzip dartsdk-linux-arm-release.zip
            rm dartsdk-linux-arm-release.zip


        - name: Use ARM Environment to Compile
          uses: uraimo/run-on-arch-action@v2
          with:
            arch: armv7
            distro: ubuntu20.04
            run: |
              export PATH=$PATH:$GITHUB_WORKSPACE/dart-sdk/bin
              mkdir dist
              dart pub get
              dart compile exe bin/nonebot_flutter_webui_agent.dart -o dist/dashboard-linux-arm



        - name: Upload Dist Artifact
          uses: actions/upload-artifact@v4
          with:
            name: dashboard-linux-arm
            path: dist/dashboard-linux-arm



  build_dashboard_index_html:
      name: Build Dashboard (html)
      runs-on: ubuntu-latest
      needs:
        - linux_amd64
        - linux_arm64
        - linux_arm
        - windows

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: Install Dependencies
          run: |
            mkdir dist
            sudo apt-get update -y && sudo apt-get upgrade -y;
            sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa


        - name: Fetch Chrome
          uses: browser-actions/setup-chrome@v1
          id: setup-chrome
        - run: export CHROME_EXECUTABLE=${{ steps.setup-chrome.outputs.chrome-path }}

        - name: Setup Flutter SDK
          uses: flutter-actions/setup-flutter@v4
          with:
            channel: stable
            version: 3.22.1

        - name: Install dependencies
          run: flutter pub get

        - name: Build Dashboard
          run: flutter build web  --pwa-strategy none --web-renderer html --release

        - name: Zip
          run: |
            cd build/
            zip -r dashboard-index-html.zip web/
            mv dashboard-index-html.zip ../dist/
            cd ..

        - name: Upload Dashboard
          uses: actions/upload-artifact@v4
          with:
            name: dashboard-index-html
            path: dist/dashboard-index-html.zip

  build_dashboard_index_canvaskit:
    name: Build Dashboard (canvaskit)
    runs-on: ubuntu-latest
    needs:
      - linux_arm64
      - linux_arm
      - linux_amd64
      - windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          mkdir dist
          sudo apt-get update -y && sudo apt-get upgrade -y;
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa


      - name: Fetch Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
      - run: export CHROME_EXECUTABLE=${{ steps.setup-chrome.outputs.chrome-path }}

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.22.1

      - name: Install dependencies
        run: flutter pub get

      - name: Build Dashboard
        run: flutter build web  --pwa-strategy none --web-renderer canvaskit --release

      - name: Zip
        run: |
          cd build/
          zip -r dashboard-index-canvaskit.zip web/
          mv dashboard-index-canvaskit.zip ../dist/
          cd ..

      - name: Upload Dashboard
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-index-canvaskit
          path: dist/dashboard-index-canvaskit.zip


  publish_releases:
    name: publish
    runs-on: ubuntu-latest
    needs:
      - build_dashboard_index_html
      - build_dashboard_index_canvaskit

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Fetch Version
        run: |
          sudo snap install yq
          nbgui_version=$(yq eval '.version' pubspec.yaml)
          echo "NBGUI_VERSION=$nbgui_version" >> $GITHUB_ENV

      - name: Download Self-host Artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: "dashboard-windows"
          path: dist/

      - name: Download Self-host Artifact (Linux AMD64)
        uses: actions/download-artifact@v4
        with:
          name: "dashboard-linux-amd64"
          path: dist/

      - name: Download Self-host Artifact (Linux ARM64)
        uses: actions/download-artifact@v4
        with:
          name: "dashboard-linux-arm64"
          path: dist/

      - name: Download Self-host Artifact (Linux ARM)
        uses: actions/download-artifact@v4
        with:
          name: "dashboard-linux-arm"
          path: dist/

      - name: Download Dashboard Artifact (html)
        uses: actions/download-artifact@v4
        with:
          name: "dashboard-index-html"
          path: dist/

      - name: Download Dashboard Artifact (canvaskit)
        uses: actions/download-artifact@v4
        with:
          name: "dashboard-index-canvaskit"
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NBGUI_VERSION }}
          body_path: RELEASE_CHANGELOG.md
          prerelease: false
          draft: false
          generate_release_notes: true
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          files: |
            dist/dashboard-windows.exe
            dist/dashboard-linux-amd64
            dist/dashboard-linux-arm64
            dist/dashboard-linux-arm
            dist/dashboard-index-html.zip
            dist/dashboard-index-canvaskit.zip




